### PR TITLE
Api updates

### LINKED ISSUE #11: Update kdbOpen
Update kdbOpen binding once ElektraInitiative/libelektra#3651 is merged

### PR DESCRIPTION
**Pull request by kodebach**
Updates for `kdbOpen` and `keyDup` changes

closes #11

**DEPENDS ON** #10

### CODE REVIEW

**Comment by kodebach** [comment]
Not sure, why the Travis build hasn't triggered here...

**Comment by markus2330** [comment]
@kodebach is it enough if the build server passed?

@raphi011 can you take a look?

**Comment by kodebach** [comment]
> is it enough if the build server passed?

Probably. But I still don't know why it hasn't triggered for this PR. Maybe Travis has problems, because this PR builds on #10?

BTW we should move from Travis to Github Actions in this repo too. Shouldn't be too hard here, the script is very short.

**Comment by markus2330** [comment]
Ok, merged #10.

**Comment by mpranj** [comment]
@kodebach do you mind if I rebase and merge #12 and #13 together to test these changes?

**Comment by mpranj** [comment]
Changes rebased & merged via #13. Thanks @kodebach

**Pull request closed without merging**
